title: "Barnyard Blitz"
# description: "A brief description of your project/site"
url: "https://seamusmcm.github.io/comp225--24/"
description: Play a fun game with your friend! Instructions at: https://github.com/SeamusMcM/comp225--24
